### ISSUE TITLE
请问一下有没有.env参考文档/配置指南？

### ISSUE THREAD

**Issue by Yang-qwq** [MoyuScript/bilibili-delete-all-dynamic#1]
如标题所示
```env
COOKIE_STRING=?
```

**Comment by MoyuScript** [comment]
![image](https://user-images.githubusercontent.com/45550579/162699595-9bda5378-f0ae-4502-8a7e-0b9186b85456.png)

到 b 站首页按 F12 进入开发者模式网络那，刷新一下然后抓一下包，cookie 请求头的值复制进去就行。
